"""The contract between LabelingWidget and its extracted modules.

The split batches (8-13) moved ~40 methods out of ``LabelingWidget``
into widget-first module functions.  Their first parameter is still the
whole widget, which makes the widget an implicit interface -- this file
makes it an explicit one: ``CONTRACT_MEMBERS`` is exactly the set of
attributes and methods those modules touch, collected mechanically
(every ``widget.X`` in the five ``utils/`` modules) and locked by
``tests/test_labeling/test_label_widget_contract.py`` from both sides:

* a module that starts touching something new fails the test until the
  contract is updated -- the growth of the interface is a deliberate
  act, not an accident;
* a contract entry whose member disappears from the widget fails the
  test -- the interface cannot silently rot.

It also documents the real size of the "god parameter": 125 members.
Any future batch that extracts a *controller class* should aim to cut
this number by owning a slice of it.
"""

CONTRACT_MEMBERS = frozenset(
    {
        "MANUAL_ZOOM",
        "_annotation_checked",
        "_apply_file_sort",
        "_batch_edit_warning_shown",
        "_config",
        "_confirm_destructive_action",
        "_convert_navigator_pos_to_canvas",
        "_create_file_list_item",
        "_current_file_item",
        "_current_review_state",
        "_decode_image_data",
        "_delete_via_context",
        "_file_item_tooltip",
        "_file_sort_mode",
        "_first_visible_row",
        "_get_rgb_by_label",
        "_label_path_for_image",
        "_load_active_thresholds",
        "_load_classes_from_folder",
        "_recent_dir_list",
        "_smart_tools_guide_message",
        "_smart_tools_guide_signature",
        "_maybe_prompt_missing_labels",
        "_next_visible_row",
        "_paging_blocked_by_drawing",
        "_position_canvas_adjustment",
        "_refresh_file_item_status_icon",
        "_refresh_file_panel",
        "_refresh_file_progress",
        "_refresh_label_panel",
        "_refresh_shape_filters",
        "_reset_label_loop",
        "_set_file_item_checked",
        "_set_file_item_review_state",
        "_should_restore_navigator",
        "_show_label_loop_popup",
        "_sync_annotation_checked_state",
        "_sync_empty_canvas_state",
        "_syncing_file_item",
        "_update_shape_color",
        "_yolo_class_names",
        "actions",
        "add_label",
        "add_recent_file",
        "adjust_scale",
        "async_exif_scanner",
        "async_label_checker",
        "attributes",
        "auto_labeling_widget",
        "batch_edit_labels",
        "brightness_contrast_dialog",
        "brightness_contrast_values",
        "cache_auto_label",
        "cache_auto_label_group_id",
        "canvas",
        "canvas_adjustment",
        "central_widget",
        "clear_auto_labeling_marks",
        "copy_file_path",
        "current_item",
        "digit_to_label",
        "error_message",
        "file_list_widget",
        "file_quality_controller",
        "filename",
        "find_last_gid",
        "find_last_label",
        "flag_widget",
        "flush_pending_auto_save",
        "fn_to_index",
        "fontMetrics",
        "get_image_file",
        "get_label_file",
        "get_next_files",
        "image",
        "image_data",
        "image_flags",
        "image_list",
        "image_path",
        "import_image_folder",
        "label_dialog",
        "label_file",
        "label_info",
        "label_list",
        "label_loop_count",
        "label_loop_shapes",
        "last_open_dir",
        "load_file",
        "load_flags",
        "load_shapes",
        "mark_checked_and_next",
        "may_continue",
        "navigator_dialog",
        "next_files_changed",
        "no_shape",
        "open_next_image",
        "other_data",
        "output_dir",
        "paint_canvas",
        "recent_files",
        "reset_attribute",
        "reset_state",
        "scale_fit_window",
        "scroll_area",
        "scroll_bars",
        "scroll_values",
        "set_clean",
        "set_dirty",
        "set_scroll",
        "set_zoom",
        "settings",
        "shape_attributes",
        "shape_dock",
        "status",
        "thumbnail_panel",
        "toggle_actions",
        "unique_label_list",
        "update_attributes",
        "update_navigator_shapes",
        "update_navigator_viewport",
        "update_thumbnail_display",
        "validate_label",
        "zoom_mode",
        "zoom_values",
        "zoom_widget",
    }
)
